### ISSUE TITLE
Tree View Scroll bar not styled 

### ISSUE THREAD

**Issue by greenhoe** [michaelhelmick/flatland-dark-ui#2]
The scroll bar for the Tree view is not styled so it really affects the dark theme, when you have enough files in the tree view where you have a scroll bar you have a very ugly default scroll bar in the middle of your editor.

**Comment by targeter21** [comment]
Recently because of the Shadow DOM changes to Atom, the vertical and horizontal scrollbars of the editor are no longer styled. I created a PR to handle that: https://github.com/michaelhelmick/flatland-dark-ui/pull/5

**Comment by michaelhelmick** [comment]
@targeter21 Does your fix in #5 solve this issue?

**Comment by targeter21** [comment]
Yes it does. I don't believe I've had an issue with the editor, so everything should be fine now.
