### ISSUE TITLE
Tree View and Editor Scrollbars Are Light

### ISSUE THREAD

**Issue by bobrocke** [michaelhelmick/flatland-dark-ui#4]
As the title says. Is this intended? Or are they to be dark, also?

**Comment by targeter21** [comment]
The editor scrollbars for me are also not normal. They should be fixed in this issue: https://github.com/michaelhelmick/flatland-dark-ui/issues/2. I believe the treeview scrollbar is styled for me under the latest Atom code, but I can double check later tonight.
